In [1]:
pip install kucoin-python

Collecting kucoin-python
  Downloading kucoin-python-1.0.6.tar.gz (16 kB)
Requirement already satisfied: requests in c:\users\igorr\anaconda3\lib\site-packages (from kucoin-python) (2.23.0)
Requirement already satisfied: websockets in c:\users\igorr\anaconda3\lib\site-packages (from kucoin-python) (8.1)
Requirement already satisfied: idna<3,>=2.5 in c:\users\igorr\anaconda3\lib\site-packages (from requests->kucoin-python) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\igorr\anaconda3\lib\site-packages (from requests->kucoin-python) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\igorr\anaconda3\lib\site-packages (from requests->kucoin-python) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\igorr\anaconda3\lib\site-packages (from requests->kucoin-python) (2020.6.20)
Building wheels for collected packages: kucoin-python
  Building wheel for kucoin-python (setup.py): started
  Building wheel for kucoin-python (setup.py): finished with status 'done'
  Created wheel for kucoin-python: filename=kucoin_python-1.0.6-py3-none-any.whl size=18822 sha256=5dd8b690573521636cc6b0f1d5dc0e7be8af798b7f8cdefe10b526d1c8653788
  Stored in directory: c:\users\igorr\appdata\local\pip\cache\wheels\34\b5\1a\77451f9bd5f40322780182cec425f6bfc2f3d8b0ea79d8bf04
Successfully built kucoin-python
Installing collected packages: kucoin-python
Successfully installed kucoin-python-1.0.6
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd
from kucoin.client import Market
client = Market(url='https://api.kucoin.com')

In [7]:
symbols = client.get_market_list()
symbols

['USDS', 'BTC', 'KCS', 'ALTS', 'DeFi', 'NFT', 'Polkadot']

In [29]:
tickers = client.get_all_tickers()
tickers = pd.DataFrame(tickers['ticker'])
tickers.set_index('symbol', inplace=True)
tickers.head().T

symbol,SHA-USDT,LOOM-BTC,BCD-BTC,BTT-ETH,OLT-BTC
symbolName,SHA-USDT,LOOM-BTC,BCD-BTC,BTT-ETH,OLT-BTC
buy,0.0047,0.00000244,0.00001971,0.00000077,0.0000001924
sell,0.004715,0.00000246,0.00002005,0.00000078,0.0000001927
changeRate,-0.0702,-0.054,-0.0408,-0.0253,0.0005
changePrice,-0.000355,-0.00000014,-0.00000084,-0.00000002,0.0000000001
high,0.005367,0.00000264,0.00002093,0.00000083,0.0000002154
low,0.004491,0.00000245,0.00001966,0.00000077,0.0000001868
vol,141943960.72966775,90177.55704216,17578.87987128,27033492.93466927,37766736.36134966
volValue,712792.61075644634271,0.2283282212289121,0.3544065552037725,21.4295975020369582,7.598003821812460328
last,0.0047,0.00000245,0.00001971,0.00000077,0.0000001924
averagePrice,0.00525847,0.00000267,0.00002025,0.00000077,0.0000002
takerFeeRate,0.001,0.001,0.001,0.001,0.001
makerFeeRate,0.001,0.001,0.001,0.001,0.001
takerCoefficient,1,1,1,1,1
makerCoefficient,1,1,1,1,1

In [ ]:
import requests
import json
import datetime
url = 'https://api.kucoin.com'

In [67]:
currencies = requests.get(url + '/api/v1/currencies')

In [72]:
currencies = currencies.json()
currencies = pd.DataFrame(currencies['data'])
currencies.set_index('currency', inplace=True)
print('There are {} currencies'.format(len(currencies)))
currencies.head().T

There are 333 currencies

currency,CSP,LOKI,NRG,FET,XMR
name,CSP,OXEN,NRG,FET,XMR
fullName,Caspian,Oxen,Energi,Fetch.Ai,Monero
precision,8,8,8,8,8
confirms,12,10,5000,12,12
contractAddress,0xa6446d655a0c34bc4f05042ee88170d056cbaf45,,,0x1d287cc25dad7ccaf76a26bc660c5f7c8e2a05bd,
withdrawalMinSize,5000,2,0.3,150,0.002
withdrawalMinFee,3000,2,0.2,48,0.001
isWithdrawEnabled,True,True,True,True,True
isDepositEnabled,True,True,True,True,True
isMarginEnabled,False,False,False,False,True
isDebitEnabled,False,True,True,False,True

In [50]:
ticker = requests.get(url + '/api/v1/market/orderbook/level1?symbol=BTC-USDT').json()
ticker['data']

{'time': 1615475368927,
 'sequence': '1614104704724',
 'price': '56977.4',
 'size': '0.001',
 'bestBid': '56971.5',
 'bestBidSize': '0.00009434',
 'bestAsk': '56971.6',
 'bestAskSize': '0.00017804'}

In [51]:
ticker_24h = requests.get(url + '/api/v1/market/stats?symbol=BTC-USDT').json()
ticker_24h['data']

{'time': 1615475556056,
 'symbol': 'BTC-USDT',
 'buy': '56998.3',
 'sell': '57000',
 'changeRate': '0.013',
 'changePrice': '736.7',
 'high': '57364',
 'low': '54238',
 'vol': '3712.3667572',
 'volValue': '208342804.860257668',
 'last': '57000',
 'averagePrice': '54559.31856369',
 'takerFeeRate': '0.001',
 'makerFeeRate': '0.001',
 'takerCoefficient': '1',
 'makerCoefficient': '1'}

In [169]:
fiat = requests.get(url + '/api/v1/prices?base=USD').json()
fiat['data']

{'LOKI': '1.01001475',
 'DFI': '3.74945229',
 'IOTX': '0.03639693',
 'MHC': '0.0167',
 'FRONT': '2.13320120',
 'MXW': '0.01922177',
 'TFD': '0.06198852',
 'DOCK': '0.09895415',
 'SUSD': '1.02366360',
 'REVV': '0.22804950',
 'STX': '1.13057958',
 'OLT': '0.01097026',
 'DENT': '0.00207008',
 'AION': '0.18767166',
 'NPXS': '0.00230893',
 'TFL': '0.31107999',
 'XNS': '0.00056870',
 'GMB': '0.00070519',
 'DGB': '0.06198852',
 'ZRX': '1.38820158',
 'META': '0.02843510',
 'BCD': '1.12091164',
 'SDT': '1.46706131',
 'IOST': '0.04492746',
 'BCH': '543.39476102',
 'CAKE': '12.64231620',
 'OMG': '5.03813102',
 'SERO': '0.10716135',
 'JST': '0.05739943',
 'POL': '0.08912092',
 'SUN': '17.12839525',
 'COFI': '0.00241698',
 'BTC': '56870.20000000',
 'CVC': '0.44984328',
 'FKX': '0.02267415',
 'OPCT': '0.09449552',
 'MIR': '6.98691200',
 'BTM': '0.08473660',
 'HPB': '0.14331290',
 'TRIAS': '0.83656064',
 'KEY': '0.00917316',
 'SNTR': '0.00000647',
 'BTT': '0.00138763',
 'ONE': '0.03980914',
 'ARX': '0.33040415',
 'ANKR': '0.04335215',
 'SUSHI': '18.34477368',
 'GOM2': '0.01762976',
 'AMIO': '0.00078088',
 'ALGO': '1.09930097',
 'SYLO': '0.00232263',
 'WBTC': '56870.20000000',
 'R': '0.01251144',
 'BU': '0.00398091',
 'ONT': '1.12375515',
 'PPT': '2.97999848',
 'DGTX': '0.00454962',
 'VELO': '1.28829887',
 'EOSC': '0.01884734',
 'DIA': '2.53811703',
 'PIVX': '1.23749555',
 'LYM': '0.02843510',
 'DERO': '2.61659790',
 'BUX': '0.48908372',
 'MANA': '0.51296920',
 'NEBL': '2.47499110',
 'KICK': '0.00002481',
 'AXPR': '0.01364885',
 'BUY': '0.08890067',
 'UBXT': '0.01933189',
 'OPEN': '0.00284351',
 'CS': '0.05800760',
 'ACT': '0.01137404',
 'CV': '0.00089286',
 'WOM': '0.19106536',
 'MKR': '2223.62482003',
 'ITC': '0.09611064',
 'ZEC': '153.82251696',
 'REN': '1.27864795',
 'CXO': '0.08758011',
 'ELA': '3.79039883',
 'ZEE': '0.91163234',
 'ADA': '1.12375515',
 'ELF': '0.29117542',
 'ADB': '0.00258191',
 'REQ': '0.10066025',
 'ZEL': '0.08530530',
 'PRE': '0.11862555',
 'LOOM': '0.13933199',
 'ZEN': '49.51206763',
 'PAX': '1.00217987',
 'UDOO': '0.03353285',
 'DOGE': '0.05573280',
 'BOLT': '0.00921297',
 'SXP': '3.53448293',
 'CHP': '0.01194843',
 'CHR': '0.48396540',
 'SHA': '0.00479416',
 'MLK': '0.62614090',
 'NANO': '5.34579880',
 'OPQ': '0.03649957',
 'WAVES': '10.03815900',
 'DX': '0.00141607',
 'CHZ': '0.38671736',
 'XRP': '0.45325549',
 'SHR': '0.03980914',
 'CUDOS': '0.04204761',
 'OCEAN': '1.36374740',
 'BEPRO': '0.00606805',
 'UMA': '24.52977760',
 'SOLVE': '0.2059',
 'VIDT': '1.09645746',
 'AVA': '3.86774230',
 'CRPT': '0.30482427',
 'VI': '0.11968553',
 'TUSD': '1.01428954',
 'XSR': '0.00278716',
 'GAS': '12.91124151',
 'RBTC': '57149.91052156',
 'NOIA': '0.40093491',
 'VSYS': '0.02217938',
 'THETA': '7.25922036',
 'ENJ': '1.81472808',
 'CAPP': '0.00241698',
 'TKY': '0.00072225',
 'WAN': '0.90196137',
 'HTR': '1.05039259',
 'GRT': '2.02405204',
 'ENQ': '0.04401753',
 'BCHABC': '253.51708357',
 'ORN': '19.40427346',
 'LEND': '1.60032743',
 'WAX': '0.18824036',
 'MASK': '13.19334018',
 'AAVE': '406.11009819',
 'UNI': '31.13756027',
 'FX': '0.15809916',
 'IDEA': '0.22024941',
 'FOTA': '0.00056870',
 'XDB': '0.06824424',
 'CKB': '0.01505923',
 'YFI': '37842.85341591',
 'XTZ': '4.12763912',
 'LUNA': '10.82808608',
 'DMG': '0.06587460',
 'HYDRA': '7.00293014',
 'AGI': '0.25875941',
 'BCHA': '16.27843375',
 'SUTER': '0.00909923',
 'EOS': '3.95134150',
 'GO': '0.04208395',
 'TIME': '11.32001331',
 'RIF': '0.32302274',
 'SWINGBY': '0.69722865',
 'SPND': '0.03518559',
 'UOS': '0.48225930',
 'HC': '1.04356817',
 'ZIL': '0.15127473',
 'FORESTPLUS': '0.00771160',
 'STRONG': '71.68417539',
 'FRM': '0.58586343',
 'XEM': '0.60054931',
 'NRG': '2.46759798',
 'MSWAP': '0.00739313',
 'VRA': '0.00742156',
 'MITX': '0.04936333',
 'ROAD': '0.00104118',
 'WTC': '1.18801848',
 'TRAC': '0.73305688',
 'BCHSV': '186.07929440',
 'COMP': '472.05455613',
 'PLAY': '0.00692110',
 'KLV': '0.14945489',
 'LYXE': '21.82228162',
 'ROOBEE': '0.00511832',
 'COMB': '0.00451411',
 'LOC': '1.77979545',
 'UQC': '11.32968124',
 'DOT': '37.05832843',
 'SENSO': '0.90935450',
 'LON': '7.13808319',
 '1INCH': '4.05058690',
 'AVAX': '31.07501468',
 'AMPL': '0.92869037',
 'DEGO': '9.32464526',
 'TOKO': '0.00568702',
 'MAN': '0.02104197',
 'UNFI': '33.81028688',
 'MAP': '0.01308015',
 'FTM': '0.44927458',
 'POWR': '0.35259524',
 'KNC': '2.19917063',
 'ALEPH': '0.33901490',
 'PHA': '0.60358350',
 'ATOM': '19.42344811',
 'TRTL': '0.00003412',
 'TONE': '0.02904361',
 'SNT': '0.09269843',
 'SNX': '21.41561121',
 'SNTVT': '0.01061767',
 'GGC': '37.85906084',
 'XHV': '13.97300814',
 'API3': '4.90455393',
 'QKC': '0.01876717',
 'ROSE': '0.16174316',
 'DAPPT': '0.00167198',
 'UBX': '0.00003992',
 'SUKU': '0.47486617',
 'DAG': '0.04873776',
 'COV': '0.35145784',
 'CHSB': '1.53322059',
 'DAI': '1.00624589',
 'ORAI': '38.91406642',
 'XYO': '0.00044927',
 'GRIN': '0.58007604',
 'DAO': '4.73387065',
 'FET': '0.45098069',
 'ETC': '12.15884876',
 'CPC': '0.01388202',
 'BNB': '293.29668246',
 'UST': '1.00035532',
 'ETH': '1798.00824297',
 'MWAT': '0.02860571',
 'NEO': '40.832803600',
 'TOMO': '2.58020097',
 'LRC': '0.57665300',
 'MTC': '0.00284351',
 'CIX100': '0.67294204',
 'ETN': '0.01391045',
 'BLOC': '0.00044681',
 'DACC': '0.00006824',
 'USDJ': '0.99112235',
 'DBC': '0.00263309',
 'VET': '0.06141982',
 'REAP': '0.16743661',
 'MTN': '0.00341221',
 'BNS': '0.05118318',
 'WEST': '0.21951897',
 'USDT': '1.00113369',
 'DASH': '239.70789300',
 'UTK': '0.49022112',
 'MTV': '0.00159237',
 'EDN': '0.00258759',
 'PMGT': '2099.64778368',
 'USDN': '1.00013255',
 'WXT': '0.00909923',
 'BOA': '0.21977888',
 'AMB': '0.07051905',
 'TRY': '0.00104072',
 'NWC': '0.18596555',
 'TRX': '0.05106944',
 'AERGO': '0.28605711',
 'LSK': '3.18416250',
 'CAG': '0.07336256',
 'NULS': '0.78878967',
 'RFUEL': '0.13844077',
 'KAI': '0.03350223',
 'DCR': '175.36665482',
 'CAS': '0.14888618',
 'LTC': '199.44379140',
 'USDC': '1.00088340',
 'WIN': '0.00022748',
 'KAT': '0.00170611',
 'WIS': '0.04379005',
 'CRO': '0.18425945',
 'CBC': '0.07279386',
 'MVP': '0.00053458',
 'CRV': '2.18847824',
 'ACAT': '0.00064263',
 'SRK': '0.02493190',
 'LTX': '0.74443092',
 'AOA': '0.00284351',
 'DRGN': '0.13193886',
 'SOUL': '0.51012569',
 'EFX': '0.15866786',
 'QNT': '40.34568759',
 'XLM': '0.40491582',
 'PLU': '6.46832475',
 'LINK': '29.37800792',
 'PLT': '0.04882529',
 'PROPS': '0.05573280',
 'QTUM': '6.08340529',
 'DATX': '0.00042084',
 'CSP': '0.00613061',
 'ACOIN': '0.85064928',
 'EWT': '15.04216790',
 'KSM': '311.20510844',
 'FIL': '42.20489296',
 'VID': '0.25250369',
 'EGT': '0.00106347',
 'NIM': '0.00810969',
 'BAT': '0.82092962',
 'BRG': '0.35202654',
 'BAX': '0.00011943',
 'AKRO': '0.03930868',
 'CTI': '0.05162846',
 'ETH2': '1798.18804383',
 'JAR': '0.00617042',
 'KCS': '4.94202038',
 'TEL': '0.00660832',
 'XMR': '223.72736680',
 'NIX': '0.17572892',
 'ARPA': '0.07735760',
 'COTI': '0.34577082',
 'PAZZI': '0.00068277'}

In [86]:
history = requests.get(url + '/api/v1/market/histories?symbol=BTC-USDT')
history = history.json()
history = pd.DataFrame(history['data'])
history['time'] = pd.to_datetime(history['time'])
history.set_index('time', inplace=True)
history

                                    sequence    price        size  side
time
2021-03-11 15:33:29.049524119  1614104816285  56136.2  0.00001205  sell
2021-03-11 15:33:29.049524119  1614104816287  56135.3  0.00043992  sell
2021-03-11 15:33:29.049524119  1614104816289  56135.3  0.00170473  sell
2021-03-11 15:33:29.049524119  1614104816291  56135.3  0.00183229  sell
2021-03-11 15:33:29.049524119  1614104816293  56135.3  0.00002564  sell
...                                      ...      ...         ...   ...
2021-03-11 15:33:34.595398618  1614104817086  56189.6  0.10336345   buy
2021-03-11 15:33:35.164441065  1614104817150  56154.4   0.2238064   buy
2021-03-11 15:33:35.364391390  1614104817156  56154.4  0.10420173   buy
2021-03-11 15:33:35.819032399  1614104817175  56154.4  0.00024328   buy
2021-03-11 15:33:35.819260858  1614104817178  56154.4  0.00020334   buy

[100 rows x 4 columns]

In [130]:
kline = requests.get(url + '/api/v1/market/candles?type=1min&symbol=BTC-USDT&startAt=1566703297&endAt=1566789757')
kline = kline.json()
kline = pd.DataFrame(kline['data'])
kline = kline.rename({0:"Time",1:"Open",
                2:"Close",3:"High",4:"Low",5:"Amount",6:"Volume"}, axis='columns')
kline.set_index('Time', inplace=True)
kline.head()

               Open    Close     High      Low       Amount            Volume
Time
1566789720  10411.5  10401.9  10411.5  10396.3  29.11357276  302889.301529914
1566789660    10416  10411.5  10422.3  10411.5  15.61781842  162703.708997029
1566789600  10408.6    10416    10416  10405.4  12.45584973   129666.51508559
1566789540  10404.7  10408.7  10415.5  10398.2    9.8995635  103014.048407233
1566789480  10413.9    10401  10416.5  10400.8  12.73438777  132554.748486241

In [145]:
kline['20 SMA'] = kline.Close.rolling(20).mean()
kline.tail()

,Open,Close,High,Low,Amount,Volume,20 SMA
Time,,,,,,,
1970-01-19 03:11:43.560,10096.2,10100,10100,10088.1,7.55044544,76195.922311066,10092.220
1970-01-19 03:11:43.500,10094,10096.1,10096.2,10092.4,5.04152542,50893.653963348,10092.755
1970-01-19 03:11:43.440,10091.7,10094,10096.7,10089.8,13.98898935,141213.970199239,10093.155
1970-01-19 03:11:43.380,10088.7,10091.7,10093.3,10084.8,3.96863773,40042.52840352,10093.575
1970-01-19 03:11:43.320,10089,10088.7,10092.1,10087.7,5.12048315,51658.509394017,10093.670

In [157]:
orderbook = requests.get(url + '/api/v1/market/orderbook/level2_20?symbol=BTC-USDT')
orderbook = orderbook.json()
orderbook

{'code': '200000',
 'data': {'time': 1615480502181,
  'sequence': '1614105117885',
  'bids': [['56730.2', '0.60053974'],
   ['56726.7', '0.00002121'],
   ['56721.2', '0.00032647'],
   ['56691.1', '0.00837133'],
   ['56690.5', '0.6'],
   ['56659.3', '1.5'],
   ['56654.5', '0.34785831'],
   ['56650', '0.01044638'],
   ['56648.8', '0.00019459'],
   ['56647.1', '0.00143616'],
   ['56646.3', '0.00017336'],
   ['56645.7', '0.0000142'],
   ['56645.6', '0.00331099'],
   ['56643.8', '0.00010459'],
   ['56642.7', '0.00259709'],
   ['56640.7', '0.00219295'],
   ['56640.4', '0.00729706'],
   ['56638.3', '0.00003682'],
   ['56638.1', '0.00018993'],
   ['56637.8', '0.00063796']],
  'asks': [['56742.1', '0.00628194'],
   ['56753.3', '0.00297055'],
   ['56764.9', '0.9941'],
   ['56766.4', '0.00099916'],
   ['56767.6', '0.00002613'],
   ['56770.8', '0.00118799'],
   ['56774.7', '0.01101992'],
   ['56777.1', '0.04144749'],
   ['56777.2', '0.00118799'],
   ['56779', '0.01297281'],
   ['56788', '0.09364352'],
   ['56794.8', '0.00034908'],
   ['56802', '0.0083'],
   ['56809.3', '0.00030439'],
   ['56810.1', '0.41285866'],
   ['56810.6', '0.0002615'],
   ['56810.7', '0.00260097'],
   ['56816', '0.00281853'],
   ['56816.1', '0.20774012'],
   ['56816.2', '0.34785831']]}}

In [160]:
bids = pd.DataFrame(orderbook['data']['bids'])
asks = pd.DataFrame(orderbook['data']['asks'])

df = pd.merge(bids, asks, left_index=True, right_index=True)
df = df.rename({"0_x":"Bid Price","1_x":"Bid Amount",
                "0_y":"Ask Price","1_y":"Ask Amount"}, axis='columns')
df.head()

  Bid Price  Bid Amount Ask Price  Ask Amount
0   56730.2  0.60053974   56742.1  0.00628194
1   56726.7  0.00002121   56753.3  0.00297055
2   56721.2  0.00032647   56764.9      0.9941
3   56691.1  0.00837133   56766.4  0.00099916
4   56690.5         0.6   56767.6  0.00002613